"""init history

Revision ID: 8508d4ee43c4
Revises: 
Create Date: 2025-09-21 21:20:13.582267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8508d4ee43c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('history_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('total_qty', sa.String(length=36), nullable=False),
    sa.Column('base_cost', sa.String(length=36), nullable=False),
    sa.Column('final_cost', sa.String(length=36), nullable=False),
    sa.Column('import_country', sa.String(length=50), nullable=False),
    sa.Column('export_country', sa.String(length=50), nullable=False),
    sa.Column('last_retrieved', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('history_id')
    )
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_index('ix_history_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_user_id'), ['user_id'], unique=False)

    op.create_table('history_tariff_line',
    sa.Column('line_id', sa.String(length=36), nullable=False),
    sa.Column('history_id', sa.String(length=36), nullable=False),
    sa.Column('line_order', sa.Integer(), nullable=False),
    sa.Column('tariff_desc', sa.String(length=255), nullable=False),
    sa.Column('tariff_type', sa.String(length=32), nullable=False),
    sa.Column('rate_str', sa.String(length=64), nullable=False),
    sa.Column('amount_str', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['history.history_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_id')
    )
    with op.batch_alter_table('history_tariff_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_tariff_line_history_id'), ['history_id'], unique=False)
        batch_op.create_index('ix_line_history_order', ['history_id', 'line_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_tariff_line', schema=None) as batch_op:
        batch_op.drop_index('ix_line_history_order')
        batch_op.drop_index(batch_op.f('ix_history_tariff_line_history_id'))

    op.drop_table('history_tariff_line')
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_user_id'))
        batch_op.drop_index('ix_history_user_created')

    op.drop_table('history')
    # ### end Alembic commands ###
