"""added country_relations table

Revision ID: f147d61fabf8
Revises: 
Create Date: 2025-09-22 09:58:53.502102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f147d61fabf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('country_id')
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countries_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_countries_name'), ['name'], unique=True)

    op.create_table('country_relations',
    sa.Column('relation_id', sa.String(), nullable=False),
    sa.Column('pair_a', sa.String(length=10), nullable=False),
    sa.Column('pair_b', sa.String(length=10), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('relation_id'),
    sa.UniqueConstraint('pair_a', 'pair_b', 'effective_date', name='uq_relations_pair_date')
    )
    with op.batch_alter_table('country_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_country_relations_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_relations_pair_a'), ['pair_a'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_relations_pair_b'), ['pair_b'], unique=False)
        batch_op.create_index('ix_relations_pair', ['pair_a', 'pair_b'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country_relations', schema=None) as batch_op:
        batch_op.drop_index('ix_relations_pair')
        batch_op.drop_index(batch_op.f('ix_country_relations_pair_b'))
        batch_op.drop_index(batch_op.f('ix_country_relations_pair_a'))
        batch_op.drop_index(batch_op.f('ix_country_relations_effective_date'))

    op.drop_table('country_relations')
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_name'))
        batch_op.drop_index(batch_op.f('ix_countries_code'))

    op.drop_table('countries')
    # ### end Alembic commands ###
